package main

import (
	"crypto/tls"
	"io"
	"log"
	"net"
	"sync"
	"time"
)

// BuildClientHello returns a real TLS ClientHello record for the given (white)
// SNI, generated by crypto/tls (no external dependency). The post-quantum
// X25519MLKEM768 key share is excluded so the record fits in one MTU.
func BuildClientHello(sni string) []byte {
	cc := &chConn{ready: make(chan struct{})}
	cfg := &tls.Config{
		ServerName:         sni,
		InsecureSkipVerify: true,
		MinVersion:         tls.VersionTLS12,
		MaxVersion:         tls.VersionTLS13,
		CurvePreferences:   []tls.CurveID{tls.X25519, tls.CurveP256, tls.CurveP384},
		NextProtos:         []string{"h2", "http/1.1"},
	}
	_ = tls.Client(cc, cfg).Handshake()
	if len(cc.written) < 40 {
		log.Fatalf("decoy ClientHello generation failed")
	}
	return cc.written
}

// chConn captures the first thing crypto/tls writes (the ClientHello) and aborts.
type chConn struct {
	written []byte
	ready   chan struct{}
	once    sync.Once
}

func (c *chConn) Write(p []byte) (int, error) {
	c.once.Do(func() { c.written = append([]byte(nil), p...); close(c.ready) })
	return len(p), nil
}
func (c *chConn) Read(p []byte) (int, error)       { <-c.ready; return 0, io.EOF }
func (c *chConn) Close() error                     { return nil }
func (c *chConn) LocalAddr() net.Addr              { return dummyAddr{} }
func (c *chConn) RemoteAddr() net.Addr             { return dummyAddr{} }
func (c *chConn) SetDeadline(time.Time) error      { return nil }
func (c *chConn) SetReadDeadline(time.Time) error  { return nil }
func (c *chConn) SetWriteDeadline(time.Time) error { return nil }

type dummyAddr struct{}

func (dummyAddr) Network() string { return "pipe" }
func (dummyAddr) String() string  { return "pipe" }

// PadClientHello pads a ClientHello record to exactly target bytes via a TLS
// padding extension (RFC 7685). The decoy must match the real ClientHello's
// length so the server cleanly drops the overlapping MD5 decoy instead of
// reassembling a mix of the two. Returns the original if it can't grow.
func PadClientHello(ch []byte, target int) []byte {
	if target <= len(ch)+4 || len(ch) < 43 {
		return ch
	}
	body := ch[5:] // handshake message
	p := 4 + 2 + 32
	if p >= len(body) {
		return ch
	}
	sidLen := int(body[p])
	p += 1 + sidLen
	csLen := int(body[p])<<8 | int(body[p+1])
	p += 2 + csLen
	cmLen := int(body[p])
	p += 1 + cmLen
	extLenPos := p
	extLen := int(body[p])<<8 | int(body[p+1])
	extEnd := p + 2 + extLen
	if extEnd > len(body) {
		return ch
	}
	padLen := target - len(ch) - 4
	padExt := make([]byte, 4+padLen)
	padExt[0], padExt[1] = 0x00, 0x15
	padExt[2], padExt[3] = byte(padLen>>8), byte(padLen)

	nb := make([]byte, 0, len(body)+len(padExt))
	nb = append(nb, body[:extEnd]...)
	nb = append(nb, padExt...)
	nb = append(nb, body[extEnd:]...)
	newExt := extLen + len(padExt)
	nb[extLenPos], nb[extLenPos+1] = byte(newExt>>8), byte(newExt)
	hsLen := len(nb) - 4
	nb[1], nb[2], nb[3] = byte(hsLen>>16), byte(hsLen>>8), byte(hsLen)

	out := make([]byte, 5+len(nb))
	copy(out[:3], ch[:3])
	out[3], out[4] = byte(len(nb)>>8), byte(len(nb))
	copy(out[5:], nb)
	return out
}
